spring:
  profiles:
    include:
      - db
  jpa:
    hibernate:
      ddl-auto: none
      properties:
        hibernates:
          show_sql: true # sysout
          format_sql: true
          use_sql_comments: true
          default_batch_fetch_size: 100

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace
#    org.hibernate.sql: debug
#    org.hibernate.type: trace # show query parameter
