spring:
  profiles:
    include:
      - db
  jpa:
    hibernate:
      ddl-auto: create
      properties:
        hibernates:
          show_sql: true # sysout
          format_sql: true


logging:
  level:
    org.hibernate.sql: debug
    org.hibernate.type: trace # show query parameter
